- hosts: "{{ hosts_tmp }}"
  vars_prompt:
  - name: "hosts_tmp"
    prompt: "¿En que servidor se actualizaran los servicios?"
    private: no
    default: vmbackup01.voip.local
  tasks:
  - name: Copiamos los ficheros de configuración comunes a los servidores
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
      force: yes
      backup: yes
    with_items:
      - { src: motd-new,                 dest: /etc/motd-new,                    mode: 755 }
      - { src: dns/resolv.conf,          dest: /etc/resolv.conf,                 mode: 755 }
      - { src: dns/db.voip.local,        dest: /etc/bind/db.voip.local,          mode: 755 }
      - { src: dns/named.conf.options,   dest: /etc/bind/named.conf.options,     mode: 755 }
      - { src: dhcp/isc-dhcp-server,     dest: /etc/default/isc-dhcp-server,     mode: 755 }
      - { src: dhcp/dhcpd.conf,          dest: /etc/default/dhcpd.conf,          mode: 755 }
      - { src: dhcp/dhcpd_replication,   dest: /etc/default/dhcpd_replication,   mode: 755 }
      - { src: drbd/r1.res,              dest: /etc/drbd.d/r1.res,               mode: 755 }
  - name: Copiamos los ficheros en el servidor principal (Master)
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
      force: yes
      backup: yes
      when: master == "yes"
    with_items:
      - { src: dns/named.conf.local.master,        dest: /etc/bind/named.conf.local,      mode: 755 }
      - { src: dhcp/dhcpd.failover.conf.primary,   dest: /etc/dhcp/dhcpd.failover.conf,   mode: 755 }
  - name: Copiamos los ficheros en el servidor secundario (Slave)
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
      force: yes
      backup: yes
      when: master == "no"
    with_items:
      - { src: dns/named.conf.local.slave,         dest: /etc/bind/named.conf.local,      mode: 755 }
      - { src: dhcp/dhcpd.failover.conf.secundary, dest: /etc/dhcp/dhcpd.failover.conf,   mode: 755 }
  - name: Habilitamos y Reiniciamos los siguientes servicios de OpenSSH
    systemd:
      name: "{{ item.service }}"
      state: started
      enabled: True
    with_items:
      - { service: sshd }