---
- hosts: pihole
  environment:
    LC_ALL: C
    LANG: C

  tasks:

  - name: Update cache (apt update)
    become: yes
    become_method: su
    become_user: root
    ansible.builtin.apt:
      update_cache: yes

  - name: Upgrade the OS (apt dist-upgrade)
    become: yes
    become_method: su
    become_user: root
    ansible.builtin.apt:
      upgrade: dist

  - name: Remove useless packages from the cache (apt autoclean)
    become: yes
    become_method: su
    become_user: root
    ansible.builtin.apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required (apt autoremove)
    become: yes
    become_method: su
    become_user: root
    ansible.builtin.apt:
      autoremove: yes
