---
- name: Kali Linux - s4vitar
  hosts: 192.168.1.120
  vars_prompt:
  - name: "user_tmp"
    prompt: "¿Cual es el username?"
    private: no
    default: user
  # https://pastebin.com/EEX1Dsuq
  # https://hack4u.io/wp-content/uploads/2022/09/bspwm_resize.txt

  tasks:

  - name: Update Server (apt update && apt dist-upgrade && apt autoclean && apt autoemove)
    become: yes
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
      autoclean: yes
      autoremove: yes
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Install Software
    become: yes
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
    ansible.builtin.apt:
      pkg:
        - build-essential
        - git
        - vim
        - libxcb-util0-dev
        - libxcb-ewmh-dev
        - libxcb-randr0-dev
        - libxcb-icccm4-dev
        - libxcb-keysyms1-dev
        - libxcb-xinerama0-dev
        - libasound2-dev
        - libxcb-xtest0-dev
        - libxcb-shape0-dev
        - libxinerama1
        - libxinerama-dev
        - kitty
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Clone git repositorie (https://github.com/baskerville/bspwm)
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
    ansible.builtin.git:
      repo: https://github.com/baskerville/bspwm
      clone: yes
      dest:  /home/{{user_tmp}}/git/bspwm
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Clone git repositorie (https://github.com/baskerville/sxhkd)
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
    ansible.builtin.git:
      repo: https://github.com/baskerville/sxhkd
      clone: yes
      dest:  ~/git/sxhkd
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Compile BSPWM
    # https://docs.ansible.com/ansible/latest/collections/community/general/make_module.html
    community.general.make:
      chdir:  ~/git/bspwm
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Install BSPWM from source
    become: yes
    # https://docs.ansible.com/ansible/latest/collections/community/general/make_module.html
    community.general.make:
      chdir:  /home/{{user_tmp}}/git/bspwm
      target: install
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Compile SXHKD
    # https://docs.ansible.com/ansible/latest/collections/community/general/make_module.html
    community.general.make:
      chdir:  ~/git/sxhkd
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Install SXHKD from source
    become: yes
    # https://docs.ansible.com/ansible/latest/collections/community/general/make_module.html
    community.general.make:
      chdir:  /home/{{user_tmp}}/git/sxhkd
      target: install
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Create directories
    file:
      path: "{{ item.path }}"
      mode: "{{ item.mode }}"
      state: directory
    with_items:
      - { path: ~/.config/bspwm,             mode: '0755'}
      - { path: ~/.config/bspwm/scripts/,    mode: '0755'}
      - { path: ~/.config/sxhkd,             mode: '0755'}
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Copy config file for BSPWM & SXHKD
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    with_items:
      - { src: bspwmrc,      dest: ~/.config/bspwm/,         mode: '0755' }
      - { src: sxhkdrc,      dest: ~/.config/sxhkd/,         mode: '0644' }
      - { src: bspwm_resize, dest: ~/.config/bspwm/scripts/, mode: '0755' }
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Change file ownership and group
    become: yes
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
    ansible.builtin.file:
      path: /usr/local/share/zsh/site-functions/_bspc
      owner: root
      group: root
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Install polybar
    become: yes
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
    ansible.builtin.apt:
      pkg:
        - cmake
        - cmake-data
        - pkg-config
        - python3-sphinx
        - libcairo2-dev
        - libxcb1-dev
        - libxcb-util0-dev
        - libxcb-randr0-dev
        - libxcb-composite0-dev
        - python3-xcbgen
        - xcb-proto
        - libxcb-image0-dev
        - libxcb-ewmh-dev
        - libxcb-icccm4-dev
        - libxcb-xkb-dev
        - libxcb-xrm-dev
        - libxcb-cursor-dev
        - libasound2-dev
        - libpulse-dev
        - libjsoncpp-dev
        - libmpdclient-dev
        - libuv1-dev
        - libnl-genl-3-dev
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Clone git repositorie (hhttps://github.com/polybar/polybar)
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
    ansible.builtin.git:
      repo: https://github.com/polybar/polybar
      clone: yes
      dest:  ~/git/polybar
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_tags.html
    tags:
      - production

  - name: Create a directory if it does not exist
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html
    ansible.builtin.file:
      path: ~/git/polybar/build
      state: directory
      mode: '0755'
    tags:
      - staging

  - name: Compile polybar
    ansible.builtin.command: /usr/bin/cmake ..
    args:
      chdir: ~/git/polybar/built
    tags:
      - staging

