#!/usr/bin/expect

## Definimos las variables que vamos a utilizar en el script
set username  "ftp_hduserp1"
set password  "temporal54"
set host      "10.113.57.62"
set directory "ip_firewall_nodo"
set timeout  -1

set filename [lindex $argv 0]

## Nos conectamos al servidor de SFTP
spawn  sftp $username@$host
expect "assword:"
send   "$password\n"
expect "sftp>"

## Realizamos la copia de seguridad de los ficheros que necesitemos
send   "cd $directory\r"
expect "sftp>"

send   "put $filename\r"
expect "sftp>"

## Movemos el fichero al nuevo destino
#send   "rename $filename ../$filename\r"
#expect "sftp>"

## Salimos del servidor SFTP
send "bye\r"