- hosts: "{{ hosts_tmp }}"
  vars_prompt:
  - name: "hosts_tmp"
    prompt: "¿En que servidor se instalara el Syslog?"
    private: no
  tasks:
  - name: Instalando el repositorio de EPEL
    yum:
      name:
        - epel-release.noarch
      state: present
  - name: Instalando paquetes genericos
    yum:
      name:
        - bash-completion
        - wget
        - git
        - screen
        - vim
        - yum-utils
        - expect
        - net-snmp
        - net-snmp-libs
        - net-snmp-utils
        - atop
        - iotop
        - htop
        - ntp
        - ntpdate
        - openssh-clients
        - libselinux-python
        - python-pip
      state: present
  - name: Instalando el repositorio de Syslog-NG para CentOS 6
    get_url:
      url: https://copr.fedorainfracloud.org/coprs/czanik/syslog-ng319epel6/repo/epel-6/czanik-syslog-ng319epel6-epel-6.repo
      dest: /etc/yum.repos.d/syslog-ng.repo
  - name: Instalando el servidor de Syslog (Syslog-NG)
    yum:
      name:
        - syslog-ng
        - syslog-ng-libdbi
        - syslog-ng-redis
      state: present
  - name: Actualizando el Sistena Operativo (CentOS 6)
    yum:
      name: '*'
      state: latest
  - name: Creando los directorios
    file:
      path: "{{ item.path }}"
      state: directory
    with_items:
      - { path: /etc/orange}
      - { path: /home/procesados}
      - { path: /home/procesados/enviados}
      - { path: /var/log/nat}
  - name: Copiamos los ficheros de configuración
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: "{{ item.mode }}"
      force: yes
      backup: yes
    with_items:
      - { src: motd,           dest: /etc/orange/motd,               mode: 755 }
      - { src: orangemain,     dest: /etc/orange/orangemain,         mode: 755 }
      - { src: orangesftp,     dest: /etc/orange/orangesftp,         mode: 755 }
      - { src: issue,          dest: /etc/issue,                     mode: 644 }
      - { src: nat,            dest: /etc/logrotate.d/nat,           mode: 644 }
      - { src: vimrc,          dest: /root/.vimrc,                   mode: 644 }
      - { src: syslog-ng.conf, dest: /etc/syslog-ng/syslog-ng.conf,  mode: 644 }
      - { src: snmpd.conf,     dest: /etc/snmp/snmpd.conf,           mode: 644 }
      - { src: ntp.conf,       dest: /etc/ntp.conf,                  mode: 644 }
      - { src: iptable,        dest: /etc/sysconfig/iptables,        mode: 644 }
      - { src: crontab,        dest: /etc/crontab,                   mode: 644 }
      - { src: sshd_config,    dest: /etc/ssh/sshd_config,           mode: 644 }
  - name: Cambio de configuracion del servicio de Syslog-NG
    replace:
      path: '/etc/syslog-ng/syslog-ng.conf'
      regexp: 'HOSTNAME-SYSLOG'
      replace: '{{ hosts_tmp }}'
  - name: Habilitamos y Reiniciamos los siguientes servicios de SYSLOG-NG, SNMPD, NTPD, SSHD
    service:
      name: "{{ item.service }}"
      state: started
      enabled: True
    with_items:
      - { service: syslog-ng}
      - { service: snmpd }
      - { service: ntpd }
      - { service: sshd }